### ISSUE TITLE
Why is there no eval folder in json_file?

### ISSUE THREAD

**Issue by rimiyeyo** [UDASE-CHiME2023/CHiME-5#3]
Hi, Why is there no eval folder in json_file?
The chime data homepage provides transcriptions.zip, but the format is different from the json_file folder you provide.
How can I create eval folder json from transcriptions.zip?

**Comment by sleglaive** [comment]
Hi @rimiyeyo,

As indicated in [this](https://www.chimechallenge.org/current/task2/data) description of the data on the CHiME Challenge website, the evaluation data (i.e., the eval folder you are mentioning) will be released 2 weeks before the submission deadline, i.e. on June 2nd.

Also, you should do not need the original transcription files of the CHiME-5 dataset to generate the data of the UDASE task.
