### ISSUE TITLE
data url not found

### ISSUE THREAD

**Issue by Janeliao-C** [UDASE-CHiME2023/CHiME-5#5]
Hello, 

I'm trying to access the data connection URL in your GitHub repository but it seems to be unavailable. The error message I'm receiving is "The requested URL was not found on this server." Could you please check if there is an issue with the link or if there are any updates needed on my end? Thank you for your help. 

Best,
Jane Liao

**Comment by sleglaive** [comment]
Hello @Janeliao-C,

The URL to download the CHiME-5 dataset changed, [here](https://www.chimechallenge.org/datasets/chime5) is the new link.

Best,

Simon

**Comment by Janeliao-C** [comment]
> Hello @Janeliao-C,
> 
> The URL to download the CHiME-5 dataset changed, [here](https://www.chimechallenge.org/datasets/chime5) is the new link.
> 
> Best,
> 
> Simon

Greatly appreciated your assistance on this issue. Thanks!

**Comment by Janeliao-C** [comment]
Dear Simon,

Thank you very much for your previous assistance. I have successfully obtained the CHiME5 data through the CHiME7 download page. But I got a new problem.

I am currently testing DNSMOS on my Chime eval/1 subset, but I am unable to achieve the same results as reported in public paper.&nbsp;I obtained some very weird results in my testing. The official metrics indicate that SIG_MOS is the highest among the three metrics at 3.48, whereas my results show BAK as the highest at 3.57, with both SIG and OVR scoring below 3.0.

I am using the same scripts as officially provided, so I suspect there might be an issue with the data I am using.&nbsp;

Could you kindly provide a few numbered samples from your test set so that I can compare and troubleshoot the data issues?

Thank you very much!

Best regards,

Jane Liao





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "UDASE-CHiME2023/CHiME-5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月4日(星期二) 下午5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [UDASE-CHiME2023/CHiME-5] data url not found (Issue #5)





 
Hello @Janeliao-C,
 
The URL to download the CHiME-5 dataset changed, here is the new link.
 
Best,
 
Simon
